### ISSUE TITLE
NFT page: History

### ISSUE THREAD

**Issue by nftgeek** [binance-chain/bsc-snapshots#27]
## Purpose
On NFT page, display transfer history table on NFT page similar to [OpenSea](https://opensea.io/assets/0xf4ee95274741437636e748ddac70818b4ed7d043/2177).
<img width="912" alt="image" src="https://user-images.githubusercontent.com/85253037/136743245-7022a80f-2be8-4943-b39f-c69166001001.png">
## Solution
- Transfer events
[Moralis Web3 API](https://admin.moralis.io/web3Api) `/nft/{address}/{token_id}/transfers` returns all transaction history of an NFT.
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/85253037/136728617-36b721c4-d771-45e4-b73a-c21daf07b736.png">

- Sale events
We have `EventsOrderMatch` table that contains all sale related data.
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/85253037/136744711-c91e65f3-63e2-4bcf-843a-a47ccc17bde9.png">

## Tasks
- [ ] Backend: Make history api. part 1 - Transfer events
- [ ] Backend: Make history api. part 2 - Sale events
- [ ] Backend: Add Moralis types to `sdk` lib to share with frontend.
- [ ] Frontend: NFT page: Add `Transfer History` table
